apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-container
  template:
    metadata:
      labels:
        app: keycloak-container
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: keycloak-container
        image: jboss/keycloak:10.0.1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 8080
        env:
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "admin"
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-container
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: keycloak-container